name: Purge jsDelivr cache

on:
  push:
    branches: [master]
    paths:
      - src/main/resources/direct.list
      - src/main/resources/ai.list
  workflow_dispatch:

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge cache
        run: |
          curl -s "https://purge.jsdelivr.net/gh/CodingJabber/aliyun-dynamic-dns/src/main/resources/direct.list"
          curl -s "https://purge.jsdelivr.net/gh/CodingJabber/aliyun-dynamic-dns/src/main/resources/ai.list"